---
  - name: Increase max_map_count
    sysctl:
      name: vm.max_map_count
      value: 262144
      sysctl_set: yes

  - name: Disable and stop vuln services
    service:
      name: dc@EnoMoloch
      state: stopped
      enabled: no

  - name: Clean local EnoMoloch cache
    become: no
    local_action:
      module: file
      path: ./services/{{ inventory_hostname }}/EnoMoloch/
      state: absent

  - name: Clone EnoMoloch locally
    become: no
    local_action:
      module: git
      repo: "git@github.com:ENOFLAG/EnoMoloch.git"
      dest: ./services/{{ inventory_hostname }}/EnoMoloch/
      accept_hostkey: yes

  - name: Copy services to vulnbox
    synchronize:
      src: ./services/{{ inventory_hostname }}/EnoMoloch/
      dest: /services/EnoMoloch/

  - name: Enable and start services
    service:
      name: dc@EnoMoloch
      state: restarted
      enabled: yes
