---
  - name: allow all loopback traffic
    iptables:
      chain: INPUT
      in_interface: lo
      jump: ACCEPT

  - name: allow related/established input traffic
    iptables:
      chain: INPUT
      ctstate: [RELATED, ESTABLISHED]
      jump: ACCEPT

  - name: allow SSH traffic
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      ctstate: NEW
      syn: match
      jump: ACCEPT

  - name: allow ICMP ping requests
    iptables:
      chain: INPUT
      protocol: icmp
      icmp_type: "8"
      jump: ACCEPT

  - name: drop all input by default
    iptables:
      chain: INPUT
      policy: DROP

  - name: drop all forward by default
    iptables:
      chain: FORWARD
      policy: DROP

  - name: persist iptables config
    shell: "iptables-save > /etc/iptables/rules.v4"

  - name: allow IPv6 loopback traffic
    iptables:
      chain: INPUT
      in_interface: lo
      jump: ACCEPT
      ip_version: ipv6

  - name: allow IPv6 related/established input traffic
    iptables:
      chain: INPUT
      ctstate: [RELATED, ESTABLISHED]
      jump: ACCEPT
      ip_version: ipv6

  - name: allow SSH traffic
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "22"
      ctstate: NEW
      syn: match
      jump: ACCEPT
      ip_version: ipv6

  - name: disable IPv6 input
    iptables:
      chain: INPUT
      policy: DROP
      ip_version: ipv6

  - name: disable IPv6 forward
    iptables:
      chain: FORWARD
      policy: DROP
      ip_version: ipv6

  - name: persist ip6tables config
    shell: "ip6tables-save > /etc/iptables/rules.v6"
