---
  # note that this is Hetzner Cloud specific and does not work if the external interface is not eth0
  - name: "Prevent access to docker services from the external interface"
    iptables:
      chain: DOCKER-USER
      action: insert
      in_interface: eth0
      jump: DROP

  - name: "Allow related/established traffic from the external interface to allow the containers to access the internet"
    iptables:
      chain: DOCKER-USER
      action: insert
      ctstate: [RELATED, ESTABLISHED]
      in_interface: eth0
      jump: ACCEPT

  - name: persist iptables config
    shell: "iptables-save > /etc/iptables/rules.v4"
