---
  - name: Disable and stop EnoEngine DB
    service:
      name: dc@EnoEngine
      state: stopped
      enabled: no

  - name: Install docker dependencies
    apt: 
      name: ["git"]
      state: present

  - name: Clone EnoEngine
    git:
      repo: "https://github.com/enowars/EnoEngine.git"
      dest: /services/EnoEngine

  - name: Enable and start EnoEngine DB
    service:
      name: dc@EnoEngine
      enabled: yes

  - name: allow scoreboard input traffic
    iptables:
      chain: INPUT
      in_interface: eth0
      destination_port: "80"
      protocol: tcp
      jump: ACCEPT

  - name: persist iptables config
    shell: "iptables-save > /etc/iptables/rules.v4"
