---
  - name: Disable and stop EnoScoreboard
    service:
      name: dc@EnoScoreboard
      state: stopped
      enabled: no

  - name: Clone EnoScoreboard
    git:
      repo: "https://github.com/enowars/EnoScoreboard.git"
      dest: /services/EnoScoreboard

  - name: Enable and start EnoScoreboard
    service:
      name: dc@EnoScoreboard
      enabled: yes

  - name: allow scoreboard input traffic
    iptables:
      action: insert
      chain: DOCKER-USER
      in_interface: eth0
      protocol: tcp
      destination_port: "8000"
      jump: ACCEPT

  - name: persist iptables config
    shell: "iptables-save > /etc/iptables/rules.v4"
