---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - docker
      - bambi-services-vuln
      - bambi-ssh-keys
      - firewall
      - docker-block-external
      - wireguard
      - EnoMoloch
