---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - bambi-ssh-keys
      - firewall
      - role: internal-routes
        vars:
          gateway: 192.168.0.1
      - role: bambi-filebeat
        vars:
          elk: 192.168.1.0
      - role: journalbeat
        vars:
          elk: 192.168.1.0
      - bambi-checkers
      - docker-block-external