---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - hetzner-base
      - docker
      - vuln_services
      - bambi-ssh-keys
      - firewall
      - docker-block-external
      - wireguard
      - EnoMoloch
      - role: programs
        vars:
          program_list: "tmux"
      - bambi-openvpn-team-server
