---
  - hosts: all
    become: yes
    become_method: sudo
    vars_files:
      - config_bambi.yml

    roles:
      - role: bambi-filebeat
        vars:
          elk: 192.168.1.0
      - bambi-ssh-keys
      - firewall
      - bambi-wireguard-router
      - role: programs
        vars:
          program_list: "tmux"
