---
  - name: Get MS gpg key
    shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg; mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/

  - name: Get deb apt list
    shell: wget -q https://packages.microsoft.com/config/debian/9/prod.list; mv prod.list /etc/apt/sources.list.d/microsoft-prod.list

  - name: Install dotnet sdk
    apt:
      name: "dotnet-sdk-3.0"
      state: present
      update_cache: yes
